# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  libraryappwebapi:
    image: libraryappwebapi
    build:
      context: .
      dockerfile: src/LibraryApp.WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5122:5122
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
